apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: argocd-zilando
  labels:
    argocd.argoproj.io/track: "true"
data:
  users.yaml: |
    users:
      - username: "app_user_4"
        password: "securepass1"
        database: "postgres"
        roles: ["read", "write"]

      - username: "admin_user"
        password: "securepass2"
        database: "postgres"
        roles: ["superuser"]
