apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresqlusers.acid.zalan.do
spec:
  group: acid.zalan.do
  scope: Namespaced
  names:
    plural: postgresqlusers
    singular: postgresqluser
    kind: PostgreSQLUser
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                database:
                  type: string
                roles:
                  type: array
                  items:
                    type: string
