apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-0-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgAFL+nHXhIAx4/sP+IbcTWymH6Sp+1OMaFvaaHPoM2vh6dOsp8y8tTjMJ9oJpq76pmvkwSyv78rhohE5ZkI2VEGP3JbdBe+SRd4CRPNx/WPxX8Hy12j0HDpyiSpKo+Nw3idMb13SYekuLQRARrdoefaPDH3X3NjNJ6uDaQNIlTru/UFo3lEl755zYYmupU4MAz5hNblcpebtb2cSwDZKeEFR+iwvyczoAxc6zxSxspL9uLfLXXInkvefvNZ1L4lckb8HVb35R6PnwrS9/CD4m2pci+sZivId3+Ixc4E1CHcCxOFi3GAAJgbog6Jalcsp9fqRrrQozJRMXVe7o1Z7ujUnqOSQA3RKZe6RQvUeTHiQDF3KvSisOFAQ6TYyXLAlEctu4uZ2js524I1UyxnJE8obU9pB48VLyhEalZb6rJvCDlY8fABtiyXn1YcI7AE0s1upSQUUX6000LF5BM54XXfysRvdLdXMA1yAR9AVKK7kP97w0VpS6O3nZeXUPBsLXUNpJNBuHWZIlp5ZL2NrTQ+0o9TrQD2+aUzLO5ukyegquQsHN9114ExdH5qt2Kfrwzo031isf5Bc4zjkVwqGZHtkLgbSwXtawVT96mwqC65SEqK96yRMsa+LDTSZUc9kEwhuvfTaYD+YtYVCzX+/HRfnVax6RsweO5ZxpzTqY7w+dOY6oFYOHMutYKBdlNCZ+fCvFQr8A==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-0-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-1-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgAsjMRixsvCgEW+tTglva8/4r6+hascw9tfA7gux+E9p2Cmi3hdmEjPFyGz6dyCkTGToz7/lMJyKSKFke+pXSvRvAUpQXDUKT7zcTtZXrLeHiV1WKrM/5Hyh7P+J4xZi6kKHLWfiiR+Y5NekqWt9Pn06Q4jf9SK9W2fgsC8UuGi7vrZ2g2jZkKdrVYh8S/oP/5Zfkmh0jsJGcSJWu9VI2jaBbmacAiayhvVX24LuL+F4D5+gIi71dO8DOP6wyQCCVliqMkWPN+gvLNCNcb6aRVTPSJMVqzNB7rkHGAz5xoLxxaFmlXN8XpBmcnmG6V41UXHGp0OZ3mTF6H0sqMba35nBGf/FsHI2jue0ZmmOw5n2H7AmKI9ojXMoQ4yxSkuEFlGmQNpMSHemYf2GPpRICN6pnOw6bJSPfGkmNRF93jnWTXuU7Kjs4jAGfCYdGvRqwZv/Er3Kn93QCg/NwCmAU4aeaZ1xAie2y8DW1tw3igDWSSEXc87xown6XkHNLada2BdwrdijdfIRnJTWZLd89SQRxjgXZ/jGZMe2DBNvIbArtuk3owzV5rTvV6URCypKPzm1WeJ/GZ7DfOLOqtTkxUA1vBR/GXt9UL9g8KbWsz1/wtIWsJ1QyuNoXTD7S4c7Pqcnf7ECU3WzqNoacLp89JjZwEVu1Nnl1gbFIqMfhi0gSpEHgnBd/mkOvjQq637EEJ1YoO8cA==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-1-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-2-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgCSLXiooBoPs+TRwK2a85Z1QUEje0ntxxBJCi4uG5GQfOWGhq0oUNkzmwR7fCYUOpAa7PQotZZbusxLO7RUsiME8PypjeXKOhNnBKDg2p6XTCcsDmuAqVH5hDimSMdKBUvp9ZCLs1A3TpS4wS6TWA85o52/0NzLaaJl/1cfFFHZxFTUYiMum5S6pV/DSNjROyhSyiUf/2ZFFn40xOUYoResFbLbiXUfbVV0I75V0cCF7VnPAsgGcvru2iNmWj+DXhSPjFaYhyz7t/YsIZVj00l177/jWhRYZEAevwP0LmQskDy0WOBu1iJjsFEU4h0+orpNt42PxMKGQ8pReFfxZTopcil7hCjMOYEjD+60LMwGDkUExHBuhbWq+PtTHpMxirQhqCY68QMZDRxi3Gk4PbufnTiCAgkbqEuReFd7dsNhqTN27DqXF9xsEGlDaToCLZzd+zjIPaY5AvarrNyvNLbwU3xxCPAYlDQV+8+A5AkWlWGKiiAccXHMOvbploOYu0BBf63sLKjI1b9Mz8DYsKSir+JtGcPwlU0g+7Y3LWwVe08hIuxmeU6dyN6u+wFGODbHaCoO5iCk1NKivhSAW2huz5SgRHjJrZd8kowO0fyWdx21bmwajayyrw63C/Ga753Lsv4AcrC5+N8K5oR8PE8snCrG4Ph1HoM3+aYTlTdcISB8bf1qHc0cABpUpWVJ54oRf8zAyw==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-2-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-3-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgCc+tWnvDgafHj/OUks/e6fZSSLEr2N9Lcsa6X9KyYFdZmR9oR1kP5Lt8/7GyZ5wDAXHKqo/IqUCeYH8B+AqsB1Tvt5+8cfU6P1eUvOk7bO43NJY54xv8SYsym1h/MwMrYZKuGO+eI5UOL9pbidi9erO0xGamHsr+n68MsjHb0EuSni/D4gEmaINBRfwCaV3k8wG7CIgOiWF1FyOysWsbG0l2fycNBbC5y4L5Joc6mD9Ied2LMWWQlK0rAoqEi/0PeEQp0V3CZMBXTszi8JK4/zPe9/KHnrOn7bH2teVWzCfYzXMkP5Yn25XNTIBNkP2PfYQ4Re3AtoS9ANjgiKWgSqkbn6CRRR8y4Ri4wTr/dW6t0s1CWrK9NGw5LVkMAF4rBVor2s0JxiKseL+g8dYvCnEscr4qPwddLwIawYp6kpzDSgewJ4+ny3Nwqu9wJQUrLbsh9Vg4OHEnAO/LmEIdYqi2xlOC2Sc2NkicL91bbYKW/+zja5cOzpTyHMgd1wbxDlX07Q+TvucU819KS3DcjEaRh9VsEhWj23OyLDr34E2h9kRVvGWJ507BJkAurBPobtofeYfFAaxrekL4TX5m8JEavwCnA2LFYepMtd/qmKbZx999mqFUY06SQQopMaU2CVZ4iKviPxyfpnUlJoF6iTs1XsgKRJ/OSSjx9KltaVC1brlTT7PqBBDALCcWxR6Y9dQi/kRg==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-3-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-15-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgAqCBUNICXKIXhlXNH8LC2WkAtuTchF2NrvYAKMFMZY11HA5Yc7Ya5jY1oD8bBEUDJKt9eQba1xS2av9h+f25Up526af3pZY76qB4KvWM1z3lTzVb3QLQ43HsHZ5ZkzqJ++uLYXFJWNW3igIB5QYRfkWUKcp8Yu2g2zCadn8MFBm0TWEAC33mqYtIzpzqCzerf1LmPdzt5amu+6hW7xCM0YVhC6s+fbG4hogm/GSfPMiUou90ssWh43NK0m8ccS8WzdGeL94QDpLK0liGwZq+IFiIaKZwRhH2BoRbE9S6re/ASXsudRsZ7DwCKvw1UB91A5m4BkDbMQ36pRKFpi2onrCxZYWSFQZlIWLppmGUIVbvj9wGra7rpRFcdBNklV8fHdX3I4yVtHZxqswCBZ7Mf3N5sVe5t0P5/yxg36oNLQUyJi3leZ6R6oyWjho560tNQBnLM/vMuM/nZjJSBTqwCxd0LHtCEwy9bUd4FKJQFoxUBWfgSOCapHtIp84UIsx5FvpfS6djmhhi1kSFvc+uwZWlHSlvjlSv+ii70PW8jmbfUSiERzIRCb6iTk+n7YAOMrMlxhDYqzKNfJz1Qsr6NEPXaw43F1W9DIukxJ+vvdNVDA3rC5K4DdJlJ7NSQOkLasUklxxlAq0s19EvDrHAtEVycE4oxMRkieYv35GcggFvpWvjUxD16xXDrWpC9IR7A8d0mVYw==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-15-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-4-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgBlbMLq3SWs3FfbQU//HGoaRlABwKZqHeZsxLSjiytf+dOg3cFI8iI9D/bfBTin/Z5I6A4Y1gx10cxXvdpa/dermLi44KHcOrrcAL3li73Kv5GFNlKN7o0BWgT4xIBorn4+UNRMIyUtjogaeeFNn9WP1igtStUZZVHh5g94vu5SoDE8CSCTPZEk4uDbRZ5aJBlFXyVQDxMue0gxrKrc3aJ45h17pNwkc0kp8xN/vJxvffxkdqxlJcFDOQTmzzFl7LtuMwXKIrYxMgvwWwyz1crybhGS6ZPKSmKrkuW2iWVCG+a8ARx/79uqmlx9xTzy4i+yOmdScKKUh/nKmQnOa5IVXq9EYN7GM3gTvAAYqhFA6Pv/R8xyKgNMgUX5NLHc8IR7309sEeV8HWwmMIQ+ayqCVMG+io1l8YnZq+1+clMuE65DWbNnxx/mhFtU1JRx/cET+AEdq7ewor/M0knjWsj7G7b1GdJ0McEfZ+6uctIV7u/ox7DQZ+aWUbLEHoNuQkvzhxJiZ22bHn40VkRpKJcmz7yigjxrWJfXu0N5ToZTcQ4CVcZT0Vr9nMjsbdyz7M5urDFxafp88X8xafAFRoLwjBp7UKCnRedCbDwvV+6XNKIC8i535dyVTH2EzOuVylQ+ya3MpAZCZvgLDtC/g11N0qOTYvpbfvh+uKY8upHt2EHTjTkzCAC0lqF6dUWYBgR51F9TIw==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-4-secret
      namespace: postgres
    type: Opaque
