apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-0-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgAyrs88o4SLDlGoT9nHfDaL0sQhIoyIWG3OKbhXFw9NT3ePUhOBixSdCtX7Y10CexlBy5L/7jPpWBDWSxPwryELoGM15ml6dEveZTn+Q7XpwtMK8tc00XWsp4eJyOfzOWam4BNoMG+osDZ1gD9AWcEwfQowOcjo9xai2jXencPJSqjZpAWFG2INPeWWRO3dBsLt5bpHKw2n96q7PvAfzluVRhmjM4hFOpQuzRfOYYqcqmElgJrE/Vq4B3yy3MhAfwan6gry40NBoprIxs4qECYihfTNyU2bTfBAjmSJRiQKy6Nb9jSAnvD0Dhb63QJpZDtm1TYbPwlUdD2c90k4zbz3AY+tvtk61Vw5M+jE0+XZa7dSEQXPJh5a7emqBX79w2FStJAosmBvhvszekbed04WWLidqcVGno2GrhxSgPCDoTpPvzDEHSFi38CwGaUI+99zTd/EM006pxpzQUo9s7qBeKBIrQquVvOQrOzYPcP7aMazw1MVFEmJDDQi2auvEZEVYEDzvDvxWFtZb4Vy3K1rqONqF/7it4UjLq7I0DtlhrZ88pwhYyi3SCD18XqYJt543iwQPLcIH0BQNhSAek1PAEJPLBq7yG2E1dUd9tvoeBXOLL+yKGldN0Bx09eni/djWcPTiSNAaTKEFgtKAvepcFc2xotYDNdJ9ya4k8r0plZxLlXLRmli2X7rjQd8cBGFsU/ZUg==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-0-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-1-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgA/hPecJE1FNyYA2335MbWzYoA57efptiKmGMOaoEHQy52LtPKJA2RLMXl777tz9JBELaqOVy56PmduNtr0ijTl2Kxg+8P1AIpveiN2eHN1UEI9rucWvCYQQULf9L7XqJVZ6Z6HlaZElks3FHpU11fTACjW4YZLadyI4qhytv38/1RPfWr344qoVMykCvS98z3b3AcmIQVW4Sq8QyYDT1UJiC9F7YQw1hji/OfKpE0KHKGA+QV+4DAqhDCyZPvvyf6HBRqa36rg3rS0N7ko2mYXno6SEiT5ViBzeJ/ijFtJKe29VbSPM+95Q1Xl4wT7Cl7SxCyWZLEmy1Bng7647z83ft00ntFBodaGwe9eNxArVa3oFBrwfzklK9DfuwjZaC+vnhJxhXpUZtbDIwk/Te8EqctnAdbJoGpBSynIHIhusctA20BjAB9+uU4ZifjpMYYp5oEbHYRjQNMKasIZm7UKmiIfKLNDZMlYhFlMlaVynes3NU9d9QKuMXPlOjm4A24GzMqfhRYxfvo2/Guy3yRVa0g30efIYqHIx9UvUwu1YEVYAcsVnKTPiowTGR3Q3Bvdrb67MXKgApXuuaeQhIRSDGvrquVkSBV3eOLzc3QqrhbeKNPJYEjcK4hsRtVDpXh+hPmSJZsqP6SwVPEfdlnrf1BW/OdlFRNrs/sMaSxEVrgI748j9PgKrqqHQudge+mjRq87MQ==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-1-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-2-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgAQzHDLgleS1kVx4dw9QWIj4LWGjlqXnGkMBwgWoxeYuPkvP8orpSGuxJZmU7jw1M0s4vkuy3t1XvnoXkWz+AbBX6jd4VRRWwViJuULdrw5UiCemKKkAZpLyIh54g+G1++nf+mAis8K4KVS2QuZaedtsgCVMrGGARRGktBpDaeqL0O/5TkwToQVoadI2iucAnwLS4BBdDab2+5K+IxTH/TdmoU3Q9T39/ILS+WWAzI0Og1V1i+UgCZHIRb4qUFFELS0m6nMuXIiEChNDwXVvxW1NGCUxflmuS1uFo/UAnACwhp54aHvzUqjsO5PhHxDZn9I2Kln0W6l9l1kRCxHkqqlcrV6cGEMnXUCr/AOFzDPV1N9MRGkNvEcSY15cloj0iWLSi9cIi/GlIXE1c5JXR+5+YW/LpuNZkF/co1FBAZ3zza1rj9kBZX6ntjYEILYNWWwFuHS3GSmcjkSETpgO/UJ6XKvjo2GKOGyquIUq//zpDlWkqiSPmWJpjOfDDAtDp14ngZvQZ1vKbQLgEmFGSMmiAEHU+ibKA+685W0xpKB+3FyCHaLBtVDmd7NrDVGv2aAC1ucPq/jjH8g3JP+EQKYBZY2b0VVRvtqWIwAHG7iQiaqn7NFnDXxnSUr3ctAiaadc1IUHdv7qg8eIkRTu24RZ1p01NWSlS0ijVL/oYHM8HYpNPYvY5h/XPE2ulLDa2QEDMRB+g==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-2-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-3-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgABj6n32YqcpDDYV1Rg9C8aSb7vNzCIhtdz2nWM6UdN6mu/UkRDl9Oujw++POlhyG45HudgEeyIQh/oxAuo+skgEM8r2jA/sYZbS7Fpgb8WF/v/LDSE/Rgm5zrl8BvGOYhQsiolVo2nlR6rcays+3PEsX3RylePU/zxZxpDEyhlIg2Wu/CJ2WHKNePQRiL3CQ/EOqIo7UUZsTHNY3BE7pObN44UhHmmF4MhcNhcCRJywe1B2VLFFAwf4yXZ8Wt9+YdTsszH0ZJvHOWfY6O/9aaDuqNTThfjgxwieV8BfMEWcxQZmiXeTczqtHJjmH6tTHjtNuppfH+s023EkspTj+bI0UKMZ2mn88LElTSMW+xbn+73UIvwacZujLI2qVFFHVVI68lb4GvHruuvlygibNLIoZFvMlyNIR70GcPX19so9sEeeOFDyjBCxjFgI3RH7jaOOhz62zaR51Gh8a3z+App5MDK3/fTRga69s+88AovJ/mksnq1eZ52gvmrCnvgFoRsd4Aw1H9cYK7DON0BmBFa8IwLEe0sWLRsYxUgx50IbT4nWgfMYDnWm0wGUs/Z+ZQHESjRN7eXVsAoTqQ91DD6j0jKVLvecTp4O0Xpry7dv3XYbU6KQiv8ILMu1eP3YBXdBK9y0ZVrlnyiAQLWKp6euGMqHfeChGvr65lzx5IZKgj5ZtU304q46sgPhglkNqoD4j/69w==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-3-secret
      namespace: postgres
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-user-4-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgCBwsHMY6g/xik8wp8u6RZD0Vw74aj0/ryG4IWAvXbcELA2wFfcxdOe5LA7s7AZmzJ4PJvdZvhKS3CGxOvnZN5OiFTCvAhuhI5/gmMbjgNrd0PcGNXsP0DrX3co2DHFiYc40Lmg6hdUSV4/zgBPbipweOH5TXlBdH8GezVVsB71b9ModqfUeUGcCThdMTBTs75ZGv/slydgyiHnFasCRx/7Upo6YSerBguPilDaapkBsp9dD9zeedhXsx8cY4L35IzX8YJrlNotlvSktkawCtB8j/qfNtwEfiPHVh6Yf0zS29EFUk+HQEPxdytIVMaTmNDfc0TrEHNTOj9yMfluVAQT5EBrkc5xkqo/G7ezET1oxwddpF1OuLtp/09M2eGTbJGHymZXxAtB7HFiO5PSkbeqZTgluXQTKxZblbRHGhiRJ0rEqaez5sHnTXjNRHLOxIumGgu7Bg8TsHgb1DP+XEIOxWeQOn9mOosj2xv7HRk1u0hYQAJ/pXO8/qkhcmMv+T4tU27UpHCFINeKap3zcUOcejlQL5l0sidHJytzus4q+XbrCvAts7opNpFbrhLYLnpPmiZsvhUKG/u7XH/R1IGjTbqjJcET4GP/Hd1RfJxw6E5XAJYMXcTm2MiObOdqFYA9WuLrsxw/kk63VLWizbwrZ6iJ8MMmK2DEfQFUD4WfKsBmRCKgD8vWKvYk/MX+1fhq/KDAwA==
  template:
    metadata:
      creationTimestamp: null
      name: user-user-4-secret
      namespace: postgres
    type: Opaque
