apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-users-config
  namespace: postgres
data:
  users.yaml: |
    users:
      - username: "test_user_2"
        password: "securepass1"
        roles: ["viewer"]
        database: "postgres"
      - username: "test_user_3"
        password: "securepass2"
        roles: ["read", "write", "super"]
        database: "postgres"
