apiVersion: v1
data:
  users.yaml: "timestamp: '2025-05-25T23:18:26.550691'\nusers:\n- database: postgres\n\
    \  roles:\n  - read\n  username: user_10\n- database: postgres\n  roles:\n  -\
    \ read\n  username: user_4\n- database: postgres\n  roles:\n  - read\n  username:\
    \ user_1\n- database: postgres\n  roles:\n  - read\n  username: user_2\n- database:\
    \ postgres\n  roles:\n  - read\n  username: user_3\n"
kind: ConfigMap
metadata:
  name: postgres-users-config
  namespace: postgres
