apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-users-config
  namespace: argocd-zilando
data:
  users.yaml: |
    users:
      - username: "app_user"
        password: "securepass1"
        database: "postgres"
        roles: ["read", "standby"]

      - username: "admin_user"
        password: "securepass3"
        database: "postgres"
        roles: ["read", "admin"]

