apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-users-config
  namespace: argocd-zilando
data:
  users.yaml: |
    users:
      - username: new_user
      - password: securepass
      - roles: ["read", "write"]
      - database: postgres
