apiVersion: v1
data:
  users.yaml: "timestamp: '2025-05-25T23:13:49.760595'\nusers:\n- database: postgres\n\
    \  roles:\n  - read\n  username: user_0\n- database: postgres\n  roles:\n  - read\n\
    \  username: user_4\n"
kind: ConfigMap
metadata:
  name: postgres-users-config
  namespace: postgres
