apiVersion: v1
data:
  users.yaml: "timestamp: '2025-04-19T22:15:55.039845'\nusers:\n- database: postgres\n\
    \  password: pass0\n  roles:\n  - read\n  username: user_0\n- database: postgres\n\
    \  password: pass4\n  roles:\n  - read\n  username: user_4\n"
kind: ConfigMap
metadata:
  name: postgres-users-config
  namespace: postgres
