apiVersion: v1
data:
  users.yaml: "timestamp: '2025-04-19T21:53:30.560031'\nusers:\n- database: postgres\n\
    \  password: pass0\n  roles:\n  - read\n  username: user_0\n"
kind: ConfigMap
metadata:
  name: postgres-users-config
  namespace: postgres
