apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-users-config
  namespace: argocd-zilando
data:
  users.yaml: |
    users:
      - username: "test_user_2"
        password: "securepass1"
        roles: ["read"]
        database: "postgres"
