apiVersion: acid.zalan.do/v1
kind: postgresqluser
metadata:
  name: new-app-user
  namespace: argocd-zilando
spec:
  username: new_app_user
  password: newpassword123
  database: postgres
  roles:
    - read

