apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-controller-sa
  namespace: postgres

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-reader
  namespace: postgres
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-user-controller
  namespace: postgres
subjects:
  - kind: ServiceAccount
    name: user-controller-sa
    namespace: postgres
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
